# EDA on Moible price prediction Data Analysis

Predict a price range, indicating how high the price of the moible is 

Here we have build the model using Logistic regression and KNN and we can conculde that Logistic regression gives us a good accuracy compared to KNN model

In [2]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [3]:
mob1=pd.read_csv(r"C:\Users\Sushmitha\Downloads\Mobile_data.csv",index_col=None,header=0,delimiter=' *, *')
mob1.head()

battery_power  clock_speed  fc  int_memory  m_dep  mobile_wt  n_cores  pc  \
0            842          2.2   1           7    0.6        188        2   2   
1           1021          0.5   0          53    0.7        136        3   6   
2            563          0.5   2          41    0.9        145        5   6   
3            615          2.5   0          10    0.8        131        6   9   
4           1821          1.2  13          44    0.6        141        2  14   

   px_height  px_width   ram  sc_h  sc_w  talk_time  price_range  
0         20       756  2549     9     7         19            1  
1        905      1988  2631    17     3          7            2  
2       1263      1716  2603    11     2          9            2  
3       1216      1786  2769    16     8         11            2  
4       1208      1212  1411     8     2         15            1

In [4]:
mob1.shape

(2000, 15)

### Pre processing

In [6]:
# checking for missing value
print(mob1.isnull().sum())

battery_power    0
clock_speed      0
fc               0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
price_range      0
dtype: int64


In [8]:
for i in mob1.columns:
    print({i:mob1[i].unique()})

{'battery_power': array([ 842, 1021,  563, ..., 1139, 1467,  858], dtype=int64)}
{'clock_speed': array([2.2, 0.5, 2.5, 1.2, 1.7, 0.6, 2.9, 2.8, 2.1, 1. , 0.9, 1.1, 2.6,
       1.4, 1.6, 2.7, 1.3, 2.3, 2. , 1.8, 3. , 1.5, 1.9, 2.4, 0.8, 0.7])}
{'fc': array([ 1,  0,  2, 13,  3,  4,  5,  7, 11, 12, 16,  6, 15,  8,  9, 10, 18,
       17, 14, 19], dtype=int64)}
{'int_memory': array([ 7, 53, 41, 10, 44, 22, 24,  9, 33, 17, 52, 46, 13, 23, 49, 19, 39,
       47, 38,  8, 57, 51, 21,  5, 60, 61,  6, 11, 50, 34, 20, 27, 42, 40,
       64, 14, 63, 43, 16, 48, 12, 55, 36, 30, 45, 29, 58, 25,  3, 54, 15,
       37, 31, 32,  4, 18,  2, 56, 26, 35, 59, 28, 62], dtype=int64)}
{'m_dep': array([0.6, 0.7, 0.9, 0.8, 0.1, 0.5, 1. , 0.3, 0.4, 0.2])}
{'mobile_wt': array([188, 136, 145, 131, 141, 164, 139, 187, 174,  93, 182, 177, 159,
       198, 185, 196, 121, 101,  81, 156, 199, 114, 111, 132, 143,  96,
       200,  88, 150, 107, 100, 157, 160, 119,  87, 152, 166, 110, 118,
       162, 127, 109, 102, 104, 

###### Insights: Here we can observe that there is no missing values in this data

In [10]:
mob1.dtypes

battery_power      int64
clock_speed      float64
fc                 int64
int_memory         int64
m_dep            float64
mobile_wt          int64
n_cores            int64
pc                 int64
px_height          int64
px_width           int64
ram                int64
sc_h               int64
sc_w               int64
talk_time          int64
price_range        int64
dtype: object

###### Insight there are no catogrical values so there is no need of converstion 

#### Creating X and Y

In [12]:
X=mob1.values[:,0:-1]
Y=mob1.values[:,-1]

In [13]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X)
X=scaler.transform(X)
#x=scaler.fit_transform(X)
print(X)

[[-0.90259726  0.83077942 -0.76249466 ... -0.78498329  0.2831028
   1.46249332]
 [-0.49513857 -1.2530642  -0.99289039 ...  1.11426556 -0.63531667
  -0.73426721]
 [-1.5376865  -1.2530642  -0.53209893 ... -0.31017108 -0.86492153
  -0.36814045]
 ...
 [ 1.53077336 -0.76274805 -0.76249466 ... -0.78498329 -1.0945264
  -1.10039396]
 [ 0.62252745 -0.76274805 -0.07130748 ...  1.35167167  0.9719174
   1.46249332]
 [-1.65833069  0.58562134  0.15908825 ...  1.58907778 -0.4057118
  -1.6495841 ]]


#### Building the model

In [18]:
from sklearn.model_selection import train_test_split

#split the data into test and train
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=10)

In [19]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(1600, 14)
(1600,)
(400, 14)
(400,)


In [16]:
#predicting using the Kneighbors_classifier

from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=int(np.sqrt(len(X_train))),metric='manhattan')

#fit the  model on the data and predict the values
model_KNN.fit(X_train,Y_train)

Y_pred=model_KNN.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(3.0, 3.0), (3.0, 2.0), (2.0, 1.0), (3.0, 3.0), (1.0, 0.0), (3.0, 3.0), (3.0, 3.0), (3.0, 3.0), (1.0, 1.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (3.0, 3.0), (2.0, 1.0), (3.0, 3.0), (2.0, 3.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (0.0, 1.0), (3.0, 2.0), (3.0, 3.0), (1.0, 1.0), (1.0, 1.0), (2.0, 2.0), (0.0, 1.0), (3.0, 3.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (1.0, 1.0), (1.0, 0.0), (2.0, 1.0), (0.0, 0.0), (3.0, 3.0), (2.0, 2.0), (2.0, 1.0), (0.0, 0.0), (1.0, 1.0), (3.0, 3.0), (1.0, 1.0), (0.0, 0.0), (1.0, 0.0), (2.0, 2.0), (1.0, 1.0), (3.0, 3.0), (2.0, 2.0), (3.0, 2.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (0.0, 0.0), (0.0, 0.0), (1.0, 1.0), (1.0, 2.0), (0.0, 1.0), (0.0, 0.0), (2.0, 2.0), (0.0, 0.0), (2.0, 2.0), (1.0, 0.0), (1.0, 2.0), (3.0, 2.0), (2.0, 2.0), (2.0, 2.0), (1.0, 0.0), (1.0, 1.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (3.0, 3.0), (2.0, 2.0), (1.0, 1.0), (3.0, 2.0), (0.0, 0.0), (1.0, 1.0), (0.

In [20]:
import numpy as np
np.sqrt(len(X_train))

40.0

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[83  9  0  0]
 [17 64 16  0]
 [ 0 21 78 10]
 [ 0  0 21 81]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.83      0.90      0.86        92
         1.0       0.68      0.66      0.67        97
         2.0       0.68      0.72      0.70       109
         3.0       0.89      0.79      0.84       102

    accuracy                           0.77       400
   macro avg       0.77      0.77      0.77       400
weighted avg       0.77      0.77      0.77       400

Accuracy of the model:  0.765


### Tunning

In [22]:
from sklearn.metrics import accuracy_score
my_dict={}
for K in range(1,31):
    model_KNN=KNeighborsClassifier(n_neighbors=K,metric='manhattan')
    model_KNN.fit(X_train,Y_train)
    Y_pred=model_KNN.predict(X_test)
    print("Accuracy is",accuracy_score(Y_test,Y_pred),'for K-Value:',K)
    my_dict[K]=accuracy_score(Y_test,Y_pred)

Accuracy is 0.53 for K-Value: 1
Accuracy is 0.4875 for K-Value: 2
Accuracy is 0.54 for K-Value: 3
Accuracy is 0.5775 for K-Value: 4
Accuracy is 0.615 for K-Value: 5
Accuracy is 0.625 for K-Value: 6
Accuracy is 0.64 for K-Value: 7
Accuracy is 0.68 for K-Value: 8
Accuracy is 0.6625 for K-Value: 9
Accuracy is 0.6825 for K-Value: 10
Accuracy is 0.695 for K-Value: 11
Accuracy is 0.7125 for K-Value: 12
Accuracy is 0.695 for K-Value: 13
Accuracy is 0.705 for K-Value: 14
Accuracy is 0.7075 for K-Value: 15
Accuracy is 0.71 for K-Value: 16
Accuracy is 0.715 for K-Value: 17
Accuracy is 0.72 for K-Value: 18
Accuracy is 0.7175 for K-Value: 19
Accuracy is 0.7325 for K-Value: 20
Accuracy is 0.7175 for K-Value: 21
Accuracy is 0.7175 for K-Value: 22
Accuracy is 0.7275 for K-Value: 23
Accuracy is 0.7325 for K-Value: 24
Accuracy is 0.7375 for K-Value: 25
Accuracy is 0.74 for K-Value: 26
Accuracy is 0.7475 for K-Value: 27
Accuracy is 0.74 for K-Value: 28
Accuracy is 0.7575 for K-Value: 29
Accuracy is 0.76

In [23]:
#to find the maximum of the value
for k in my_dict:
    if my_dict[k]==max(my_dict.values()):
        print(k,':',my_dict[k])

30 : 0.765


In [24]:
#predicting using the Kneighbors_classifier

from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=30,metric='manhattan')

#fit the  model on the data and predict the values
model_KNN.fit(X_train,Y_train)

Y_pred=model_KNN.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(3.0, 3.0), (3.0, 2.0), (2.0, 1.0), (3.0, 3.0), (1.0, 0.0), (3.0, 3.0), (3.0, 2.0), (3.0, 3.0), (1.0, 1.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (3.0, 3.0), (2.0, 1.0), (3.0, 3.0), (2.0, 3.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (0.0, 0.0), (3.0, 3.0), (3.0, 3.0), (1.0, 1.0), (1.0, 1.0), (2.0, 2.0), (0.0, 1.0), (3.0, 3.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (1.0, 1.0), (1.0, 0.0), (2.0, 1.0), (0.0, 0.0), (3.0, 3.0), (2.0, 2.0), (2.0, 2.0), (0.0, 1.0), (1.0, 1.0), (3.0, 3.0), (1.0, 1.0), (0.0, 0.0), (1.0, 0.0), (2.0, 2.0), (1.0, 1.0), (3.0, 2.0), (2.0, 2.0), (3.0, 2.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (0.0, 0.0), (0.0, 0.0), (1.0, 1.0), (1.0, 1.0), (0.0, 0.0), (0.0, 0.0), (2.0, 2.0), (0.0, 0.0), (2.0, 2.0), (1.0, 0.0), (1.0, 2.0), (3.0, 2.0), (2.0, 2.0), (2.0, 2.0), (1.0, 0.0), (1.0, 1.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (3.0, 3.0), (2.0, 2.0), (1.0, 1.0), (3.0, 2.0), (0.0, 0.0), (1.0, 1.0), (0.

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[83  9  0  0]
 [17 64 16  0]
 [ 0 21 78 10]
 [ 0  0 21 81]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.83      0.90      0.86        92
         1.0       0.68      0.66      0.67        97
         2.0       0.68      0.72      0.70       109
         3.0       0.89      0.79      0.84       102

    accuracy                           0.77       400
   macro avg       0.77      0.77      0.77       400
weighted avg       0.77      0.77      0.77       400

Accuracy of the model:  0.765


###### Insight: Here we can observe that base model even after tunning gives us almost the same accuarcy

# Logistic Regression

In [28]:
#Recreating X and Y
X=mob1.values[:,0:-1]
Y=mob1.values[:,-1]

In [29]:
from sklearn.model_selection import train_test_split

#split the data into test and train
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=10)

In [30]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(1600, 14)
(1600,)
(400, 14)
(400,)


In [31]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [32]:
from sklearn.linear_model import LogisticRegression
#create a model object
classifier=LogisticRegression(multi_class='multinomial')
#train the model object
classifier.fit(X_train,Y_train)# fit function is used to train the model

Y_pred=classifier.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(3.0, 3.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (1.0, 1.0), (3.0, 3.0), (3.0, 3.0), (3.0, 3.0), (1.0, 1.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (0.0, 0.0), (3.0, 2.0), (3.0, 3.0), (1.0, 1.0), (1.0, 1.0), (2.0, 2.0), (0.0, 0.0), (3.0, 3.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (1.0, 1.0), (1.0, 1.0), (2.0, 2.0), (0.0, 0.0), (3.0, 3.0), (2.0, 2.0), (2.0, 2.0), (0.0, 0.0), (1.0, 1.0), (3.0, 3.0), (1.0, 1.0), (0.0, 0.0), (1.0, 1.0), (2.0, 2.0), (1.0, 1.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (0.0, 0.0), (0.0, 0.0), (1.0, 1.0), (1.0, 1.0), (0.0, 0.0), (0.0, 0.0), (2.0, 2.0), (0.0, 0.0), (2.0, 2.0), (1.0, 1.0), (1.0, 2.0), (3.0, 3.0), (2.0, 2.0), (2.0, 2.0), (1.0, 1.0), (1.0, 1.0), (3.0, 3.0), (2.0, 1.0), (3.0, 3.0), (3.0, 3.0), (2.0, 2.0), (1.0, 1.0), (3.0, 2.0), (0.0, 0.0), (1.0, 0.0), (0.

In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 92   0   0   0]
 [  2  94   1   0]
 [  0   5 102   2]
 [  0   0   3  99]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99        92
         1.0       0.95      0.97      0.96        97
         2.0       0.96      0.94      0.95       109
         3.0       0.98      0.97      0.98       102

    accuracy                           0.97       400
   macro avg       0.97      0.97      0.97       400
weighted avg       0.97      0.97      0.97       400

Accuracy of the model:  0.9675


### Insight: So overall we can conclude that logistic regression works well when compared to KNN model